name: TorosamyScript
main: net.torosamy.torosamyScript.TorosamyScript
version: '${project.version}'
author: '${plugin.yml.author}'
website: '${plugin.yml.website}'
api-version: '${plugin.yml.api}'
depend:
  - TorosamyCore
